# 1. Kredensial Database
apiVersion: v1
kind: Secret
metadata:
  name: identity-db-secret
type: Opaque
data:
  # Hasil echo -n "admin" | base64
  POSTGRES_USER: YWRtaW4=
  # Hasil echo -n "rahasia123" | base64
  POSTGRES_PASSWORD: cmFoYXNpYTEyMw==

---

# 2. Akses Jaringan (Lokal & Internal Cluster)
apiVersion: v1
kind: Service
metadata:
  name: identity-db-service
spec:
  type: NodePort # Ubah dari ClusterIP/None menjadi NodePort
  selector:
    app: identity-db
  ports:
    - protocol: TCP
      port: 5432       # Port di dalam cluster
      targetPort: 5432 # Port di dalam container
      nodePort: 30432  # Port yang bisa diakses dari laptop (bebas pilih 30000-32767)

---

# 3. Unit Utama Database & Penyimpanan Data
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: identity-db
spec:
  serviceName: "identity-db-service"
  replicas: 1
  selector:
    matchLabels:
      app: identity-db
  template:
    metadata:
      labels:
        app: identity-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
          # Mapping dari Secret ke Environment Variable Postgres
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: identity-db-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: identity-db-secret
                key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
  # Template untuk membuat Disk (PVC) secara otomatis
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi