apiVersion: v1
kind: Secret
metadata:
  name: identity-db-secret
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: cmFoYXNpYTEyMw==

apiVersion: v1
kind: Service
metadata:
  name: identity-db-service
spec:
  selector:
    app: identity-db
  ports:
    - protocol: TCP
      port: 5432
  clusterIP: None # Kita gunakan Headless Service untuk StatefulSet

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: identity-db
spec:
  serviceName: "identity-db-service"
  replicas: 1
  selector:
    matchLabels:
      app: identity-db
  template:
    metadata:
      labels:
        app: identity-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        envFrom:
        - secretRef:
            name: identity-db-secret
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi